const feats = [
    {
      name: 'Take Aim',
      type: 'Combat',
      prerequisites: 'Gun 1+',
      cost: '',
      description: 'Unlock Aim action',
    },
    {
      name: 'Disengage',
      type: 'Combat',
      prerequisites: 'Melee 1+',
      cost: '',
      description: 'Unlock Disengage action',
    },
    {
      name: 'Grapple',
      type: 'Combat',
      prerequisites: 'Melee 1+',
      cost: '',
      description: 'Unlock Grapple action',
    },
    {
      name: 'Disarm',
      type: 'Combat',
      prerequisites: 'Melee 1+ or Gun 2+',
      cost: '',
      description: 'Unlock Disarm action',
    },
    {
      name: 'Charge',
      type: 'Combat',
      prerequisites: 'Melee 1+',
      cost: '',
      description: 'Unlock Charge action',
    },
    {
      name: 'Called Shot',
      type: 'Combat',
      prerequisites: 'Gun 1+',
      cost: '',
      description: 'Unlock Called Shot action',
    },
    {
      name: 'Called Shot (Adv.)',
      type: 'Combat',
      prerequisites: 'Called Shot & Gun 3+',
      cost: '',
      description: 'Unlock Called Shot (Adv.) action',
    },
    {
      name: 'Inspiring Speech',
      type: 'Combat',
      prerequisites: 'Tactics or leadership 0+',
      cost: '',
      description: 'Unlock Inspiring Speech action',
    },
    {
      name: 'Sustained Fire',
      type: 'Combat',
      prerequisites: 'Gun 2+',
      cost: '',
      description: 'Unlock Full Auto Attack action',
    },
    {
      name: 'Overwatch',
      type: 'Combat',
      prerequisites: 'Gun 2+',
      cost: '',
      description: 'Unlock Overwatch action',
    },
    {
      name: 'Controlled Burst',
      type: 'Combat',
      prerequisites: 'Gun 2+',
      cost: '',
      description: 'Unlock Controlled Burst action',
    },
    {
      name: 'Experienced Brawler',
      type: 'Combat',
      prerequisites: 'Total 10+',
      cost: '',
      description: 'Unlock Dodge action',
    },
    {
      name: 'Duelist',
      type: 'Combat',
      prerequisites: 'Melee 1+',
      cost: '',
      description: 'Unlock Parry action',
    },
    {
      name: 'Dive for Cover',
      type: 'Combat',
      prerequisites: 'Athletics 1+',
      cost: '',
      description: 'Unlock Dive for Cover action',
    },
    {
      name: 'Opportunist',
      type: 'Combat',
      prerequisites: 'Melee 1+',
      cost: '',
      description: 'Unlock Attack of Opportunity action',
    },
    {
      name: 'Friendly Face',
      type: 'General',
      prerequisites: 'Carouse 1+',
      cost: '',
      description: 'After 1 hr socializing, you meet someone willing to do you a small favor or answer one reasonable question. Requires successful check, can also fail and be lied to.',
    },
    {
      name: 'Smuggler',
      type: 'General',
      prerequisites: 'Broker & Deception 1+',
      cost: '',
      description: 'Can smuggle one item anywhere with a deception check',
    },
    {
      name: 'Experienced Smuggler',
      type: 'General',
      prerequisites: 'Smuggler feat, Deception & Broker 2+',
      cost: '',
      description: 'Can smuggle 3 items anywhere with a deception check',
    },
    {
      name: 'Bureaucratic Shortcut',
      type: 'General',
      prerequisites: 'Admin 1+',
      cost: '',
      description: 'You may reduce the time required for one bureaucratic task by one step (days → hours → minutes)',
    },
    {
      name: 'Know a Guy',
      type: 'General',
      prerequisites: 'Streetwise 1+',
      cost: '',
      description: 'Once per settlement, declare the existence of a local contact capable of providing one useful piece of information or arranging a minor illicit service. Takes several hours, and a successful roll.',
    },
    {
      name: 'Legal Objection',
      type: 'General',
      prerequisites: 'Advocate 2+',
      cost: '',
      description: 'When NPC attempts to arrest, search, or detain someone, cite a legal objection. With successful roll, attempt is ended.',
    },
    {
      name: 'Polyglot',
      type: 'General',
      prerequisites: 'Language 0+',
      cost: '',
      description: 'Learn a new language of your choice.',
    },
    {
      name: 'Quick Hack',
      type: 'General',
      prerequisites: 'Electronics 1+',
      cost: '',
      description: 'Lowers the time to hack a device by one degree, hours -> minutes -> seconds.',
    },
    {
      name: 'Combat Hack',
      type: 'Combat',
      prerequisites: 'Electronics 2+',
      cost: '',
      description: 'Unlock Combat Hack action.',
    },
    {
      name: 'Divide and Conquer',
      type: 'Combat',
      prerequisites: 'Persuade 1+',
      cost: '',
      description: "Apply confusion to X NPC's. X difficulty start at 8+, increase by 2 for each additional target.",
    },
    {
      name: 'Diplomatic Gambit',
      type: 'General',
      prerequisites: 'Diplomat 1+',
      cost: '',
      description: 'Change the attitude of any NPC by one degree with a successful check, lowers with failure',
    },
    {
      name: 'Keen Eye',
      type: 'Combat',
      prerequisites: 'Recon 0 or Total>=10',
      cost: '',
      description: 'Unlock Identify Enemy action',
    },
    {
      name: 'Combat Sprint',
      type: 'Combat',
      prerequisites: 'Athletics 2+',
      cost: '',
      description: 'Unlock Combat Sprint action',
    },
    {
      name: 'Count the Odds',
      type: 'General',
      prerequisites: 'Gambling 1+',
      cost: '',
      description: 'Once per session, after observing one round, you can immediately determine if the game is honest, manipulated, or fraudulent.',
    },
    {
      name: 'Convincing Argument',
      type: 'General',
      prerequisites: 'Persuade 2+',
      cost: '',
      description: "Once per session, you can convince any normal or rare NPC of your argument as long as it does not directly harms the NPC or his interests.",
    },
  ];

export default feats